dependencies:
  override:
    - gradle publish

general:
  artifacts:
    - "spoils-common/build/libs"
    - "spoils-core/build/libs"
    - "spoils-api/build/libs"

test:
  override:
    - gradle test